# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  python36-docker:
    docker:
      - image: circleci/python:3.6.10
    resource_class: medium

commands:
  test_urbamt:
    
    parameters:
      model_name:
        type: string
    steps:
      - checkout
      - run:
          name: "Install package"
          command: |
            pip install .[dev]
      - run:
          name: "Test translation"
          command: |
            pytest tests/test_en_to_vi.py
      
jobs:
  test_urbamt:
    executor: python36-docker
    steps:
      -  test_urbamt:

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - test_urbamt